import type { ASTNode } from './ASTGenerator';

export class SourceComposer {
  public compose(ast: ASTNode, templateContent: string): string {
    let sourceCode = `// Generated by MONI SourceComposer\n\n`;
    sourceCode += `// AST Node: ${ast.type} - ${ast.name}\n`;
    sourceCode += templateContent;

    if (ast.children) {
      for (const child of ast.children) {
        sourceCode += `\n// Declaring: ${child.name} (${child.type})\n`;
        if (child.children) {
          for (const grand of child.children) {
            sourceCode += `  // Action: ${grand.name}\n`;
          }
        }
      }
    }

    return sourceCode;
  }
}
