export class ToolGenerator {
  public generateToolMetadata(toolName: string): string {
    return `export const ${toolName}Tool = {\n  name: "${toolName}",\n  description: "Autonomous tool generated by MONI",\n  parameters: {\n    type: "object",\n    properties: { id: { type: "string" } }\n  }\n};\n`;
  }
}
